/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud.sql;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JList;
import javax.swing.Timer;
import crud.sql.EmptyFieldException;
/**
 *
 * @author Muhammad Shaheer
 */
public class CrudFrontEnd extends javax.swing.JFrame {
    

    /**
     * Creates new form CFE
     */
    EmployeeDao ed = new EmployeeDao();
    public CrudFrontEnd() {
        initComponents();
        ed.fillDataJList(jList1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        empname_tf = new javax.swing.JTextField();
        empphone_tf = new javax.swing.JTextField();
        empcity_tf = new javax.swing.JTextField();
        heading = new javax.swing.JLabel();
        empid_label = new javax.swing.JLabel();
        empname_label = new javax.swing.JLabel();
        empphone_label = new javax.swing.JLabel();
        empcity_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        empid_label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management System");

        empname_tf.setToolTipText("enter employee name");
        empname_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empname_tfActionPerformed(evt);
            }
        });

        empphone_tf.setToolTipText("enter employee phone number");
        empphone_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empphone_tfActionPerformed(evt);
            }
        });

        empcity_tf.setToolTipText("enter city");
        empcity_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empcity_tfActionPerformed(evt);
            }
        });

        heading.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Employee Management System");

        empid_label.setText("Employee ID: ");

        empname_label.setText("Employee Name: ");

        empphone_label.setText("Employee Phone:");

        empcity_label.setText("Employee City:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("VIEW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        empid_label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setToolTipText("");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(heading)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(empcity_label)
                                            .addComponent(empphone_label)
                                            .addComponent(empname_label)
                                            .addComponent(empid_label))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(empphone_tf)
                                            .addComponent(empcity_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                            .addComponent(empname_tf)
                                            .addComponent(empid_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empid_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empid_label))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empname_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empphone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empphone_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empcity_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empcity_label))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void empphone_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empphone_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empphone_tfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Insert
        String name = empname_tf.getText();
        String phone = empphone_tf.getText();
        String city = empcity_tf.getText();
        
        Employee emp = new Employee(name,phone,city);
        
        boolean answer = EmployeeDao.insertEmployeeToDB(emp);
        
       if (answer) { 
           jLabel1.setText("Successfully added!");
       Timer timer = new Timer(2000, event -> {
                jLabel1.setText("");
            });
       timer.setRepeats(false);
            timer.start();
       }
       
       ed.fillDataJList(jList1);
       
       empname_tf.setText("");
       empphone_tf.setText("");
       empcity_tf.setText("");
       


       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //delete
         
try {
             Connection con = ConnectionProcedure.createC();
             String q = "DELETE FROM employee WHERE ename = ?";
             PreparedStatement pstmt = con.prepareStatement(q);
             
             String name = jList1.getSelectedValue().toString();
             pstmt.setString(1, name);
             
            pstmt.execute();
             
             ed.fillDataJList(jList1);

                      
                   
         } catch(Exception e) {
             e.printStackTrace();
         }
         return;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void empname_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empname_tfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_empname_tfActionPerformed

    private void empcity_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empcity_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empcity_tfActionPerformed
 

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       boolean flag = false;
         //jdbc code..
           ResultSet rs = null;
           PreparedStatement pstmt = null;
           Connection con = ConnectionProcedure.createC();
     
         try {             
             String q = "SELECT * FROM employee WHERE ename=?";
             pstmt = con.prepareStatement(q);
             String name = jList1.getSelectedValue().toString();
             pstmt.setString(1, name);
             rs = pstmt.executeQuery();
             //set value of parameter
             
             
             while (rs.next()) {
                String eid = rs.getString("eid");
                empid_label2.setText(eid);
                
                empname_tf.setText(name);
                
                String ephone = rs.getString("ephone");
                empphone_tf.setText(ephone);
                
                String empcity = rs.getString("ecity");
                empcity_tf.setText(empcity);
                
            }
             
             
             flag = true;
      
         } catch(Exception e) {
             System.out.print("Too long");
             e.printStackTrace();
         }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //UPDATE
        boolean flag = false;
         //jdbc code..
           ResultSet rs = null;
           PreparedStatement pstmt = null;
           Connection con = ConnectionProcedure.createC();
           
         try {             
             String q = "UPDATE employee SET ename=?,ephone=?,ecity=? WHERE ename=?";
             pstmt = con.prepareStatement(q);
             String name = jList1.getSelectedValue().toString();
             
             String empname_field = empname_tf.getText();
             String empphone_field = empphone_tf.getText();
             String empcity_field = empcity_tf.getText();

             if (empname_field.equals("") || empphone_field.equals("") || empcity_field.equals("")) {
                 throw new EmptyFieldException();
             }
             else {
             pstmt.setString(1, empname_field);
             pstmt.setString(2, empphone_field);
             pstmt.setString(3, empcity_field);
             pstmt.setString(4, name);
             }
             
             pstmt.execute();
             ed.fillDataJList(jList1);
      
          } catch (EmptyFieldException efe) {
              jLabel1.setForeground(Color.RED);
               jLabel1.setText("NO EMPTY FIELD ALLOWED!");
       Timer timer = new Timer(2000, event -> {
                jLabel1.setText("");
            });
       timer.setRepeats(false);
            timer.start();
          } 
         catch(NullPointerException npe) {
               jLabel1.setForeground(Color.RED);
               jLabel1.setText("Please select something first!");
       Timer timer = new Timer(2000, event -> {
                jLabel1.setText("");
            });
       timer.setRepeats(false);
            timer.start();
           }
         catch(Exception e) {
             System.out.print("Too long");
             e.printStackTrace();
         }
           
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
              jList1 = (JList)evt.getSource();

            // Double-click detected
            int index = jList1.locationToIndex(evt.getPoint());
            boolean flag = false;
         //jdbc code..
           ResultSet rs = null;
           PreparedStatement pstmt = null;
           Connection con = ConnectionProcedure.createC();
     
         try {             
             String q = "SELECT * FROM employee WHERE ename=?";
             pstmt = con.prepareStatement(q);
             String name = jList1.getSelectedValue().toString();
             pstmt.setString(1, name);
             rs = pstmt.executeQuery();
             //set value of parameter
             
             
             while (rs.next()) {
                String eid = rs.getString("eid");
                empid_label2.setText(eid);
                
                empname_tf.setText(name);
                
                String ephone = rs.getString("ephone");
                empphone_tf.setText(ephone);
                
                String empcity = rs.getString("ecity");
                empcity_tf.setText(empcity);
                
            }
             
             
             flag = true;
      
         } catch(Exception e) {
             System.out.print("Too long");
             e.printStackTrace();
         }
        }
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudFrontEnd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel empcity_label;
    private javax.swing.JTextField empcity_tf;
    private javax.swing.JLabel empid_label;
    public javax.swing.JLabel empid_label2;
    private javax.swing.JLabel empname_label;
    private javax.swing.JTextField empname_tf;
    private javax.swing.JLabel empphone_label;
    private javax.swing.JTextField empphone_tf;
    private javax.swing.JLabel heading;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

  
}
